services:

  api:
    build: .
    ports:
      - "8000:8000"

    environment:
      REDIS_URL: redis://redis:6379
      RATE_LIMIT_CAPACITY: 10
      RATE_LIMIT_REFILL_RATE: 1
      IP_RATE_LIMIT_CAPACITY: 10
      IP_RATE_LIMIT_REFILL_RATE: 1

      USER_RATE_LIMIT_CAPACITY: 20
      USER_RATE_LIMIT_REFILL_RATE: 2

      API_KEY_RATE_LIMIT_CAPACITY: 50
      API_KEY_RATE_LIMIT_REFILL_RATE: 5
      SEARCH_IP_RATE_LIMIT_CAPACITY: 5
      SEARCH_IP_RATE_LIMIT_REFILL_RATE: 1

      SEARCH_USER_RATE_LIMIT_CAPACITY: 10
      SEARCH_USER_RATE_LIMIT_REFILL_RATE: 2

      SEARCH_API_KEY_RATE_LIMIT_CAPACITY: 25
      SEARCH_API_KEY_RATE_LIMIT_REFILL_RATE: 5

      UPLOAD_IP_RATE_LIMIT_CAPACITY: 2
      UPLOAD_IP_RATE_LIMIT_REFILL_RATE: 0.5

      UPLOAD_USER_RATE_LIMIT_CAPACITY: 5
      UPLOAD_USER_RATE_LIMIT_REFILL_RATE: 1

      UPLOAD_API_KEY_RATE_LIMIT_CAPACITY: 10
      UPLOAD_API_KEY_RATE_LIMIT_REFILL_RATE: 2
    
    depends_on:
      redis:
        condition: service_healthy

  redis:
    image: redis:7-alpine

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5